[package]
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"
name = "solana-validator-checker"
version = "0.1.0"

[dependencies]
dotenv = "0.15.0"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8"